On pull request, compare to nightly linting

diff --git a/.github/workflows/dunedaq-develop-cpp-ci.yml b/.github/workflows/dunedaq-develop-cpp-ci.yml
--- a/.github/workflows/dunedaq-develop-cpp-ci.yml
+++ b/.github/workflows/dunedaq-develop-cpp-ci.yml
@@ -187,3 +187,23 @@ jobs:
       with:
         name: linting_results
         path: ${{ github.workspace }}/dev-${{ matrix.os_name }}/log/linting*/*_linting.log
+
+    - name: Download nightly linting results
+      if: ${{ github.event_name == 'pull_request' }}
+      uses: actions/download-artifact@main
+      with:
+        name: linting_results
+        path: ${{ github.workspace }}/dev-${{ matrix.os_name }}/nightly_linting_results.log 
+
+    - name: Compare to nightly linting results
+      if: ${{ github.event_name == 'pull_request' }}
+      run: |
+        pr_linting_results_file=$(dev-${{ matrix.os_name }}/log/linting*/*_linting.log)
+        nightly_linting_results_file=$(dev-${{ matrix.os_name }}/nightly_linting_results.log)
+        [[ -f "$pr_linting_results_file" ]] || echo "ERROR: No PR results file; exit 1"
+        [[ -f "$nightly_linting_results_file" ]] || echo "ERROR: No nightly results file; exit 2"
+        if ! diff "$pr_linting_results_file" "$nightly_linting_results_file" > linting_diff.txt; then
+          echo "ERROR: This PR introduces new linting errors:"
+          cat linting_diff.txt
+          exit 1
+        fi
